import type { InstrumentRow } from '../utils/types';

export const mockInstrumentRows: InstrumentRow[] = [
  {
    area: 'Ammonia',
    equipmentType: 'Flow Transmitter',
    tagNumber: 'FT-1001',
    equipmentDescription: 'Ammonia Feed Flow',
    status: 'Healthy',
    alarmDescription: '',
    rectification: '',
    notificationDate: new Date('2024-01-15'),
    notificationDateDisplay: '2024-01-15',
  },
  {
    area: 'Ammonia',
    equipmentType: 'Pressure Transmitter',
    tagNumber: 'PT-1002',
    equipmentDescription: 'Reactor Pressure',
    status: 'Caution',
    alarmDescription: 'High pressure alarm',
    rectification: 'Calibrate sensor',
    notificationDate: new Date('2024-01-20'),
    notificationDateDisplay: '2024-01-20',
  },
  {
    area: 'Utility',
    equipmentType: 'Temperature Transmitter',
    tagNumber: 'TT-2003',
    equipmentDescription: 'Converter Temperature',
    status: 'Warning',
    alarmDescription: 'ALS - Obsolete model',
    rectification: 'Replace with new model',
    notificationDate: new Date('2024-01-25'),
    notificationDateDisplay: '2024-01-25',
  },
  {
    area: 'Urea',
    equipmentType: 'Level Transmitter',
    tagNumber: 'LT-3004',
    equipmentDescription: 'Storage Tank Level',
    status: 'Healthy',
    alarmDescription: '',
    rectification: '',
    notificationDate: new Date('2024-02-01'),
    notificationDateDisplay: '2024-02-01',
  },
  {
    area: 'System',
    equipmentType: 'Actuator',
    tagNumber: 'AC-4003',
    equipmentDescription: 'Emergency Shutdown Valve',
    status: 'Warning',
    alarmDescription: 'ALS - Obsolete firmware',
    rectification: 'Upgrade firmware',
    notificationDate: new Date('2024-01-30'),
    notificationDateDisplay: '2024-01-30',
  },
];
